name: Compilar Nhaldûrico Keyboard

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ""

      - name: Aceptar licencias
        run: yes | sdkmanager --licenses

      - name: Instalar SDK 35
        run: sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Compilar APK
        run: gradle assembleDebug --stacktrace

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: NhalduricoKeyboard
          path: app/build/outputs/apk/debug/app-debug.apk
