name: Compilar Nhaldûrico Keyboard

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Extraer proyecto
        run: |
          mkdir proyecto
          unzip -q "NhaldûricoKeyboard_v1.1_GitHub_corregido.zip" -d proyecto

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar Android SDK 35
        run: sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Compilar APK
        working-directory: proyecto
        run: gradle assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: NhalduricoKeyboard
          path: proyecto/app/build/outputs/apk/debug/app-debug.apk
