- name: Aceptar licencias de Android
  run: yes | sdkmanager --licenses || true

- name: Instalar Android SDK 35
  run: sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Compilar APK
        run: gradle assembleDebug --stacktrace

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: NhalduricoKeyboard
          path: app/build/outputs/apk/debug/app-debug.apk
